name: Train and Deploy Model

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r predictive-maintenance/requirements.txt
    
    - name: Prepare model directory
      run: mkdir -p predictive-maintenance/models

    - name: Train model
      run: |
        python predictive-maintenance/src/train.py predictive-maintenance/data/engine_data.csv

    - name: Deploy model
      run: |
        python predictive-maintenance/deploy/deploy.py
