name: Train and Deploy Model.2

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Clear old workspace
      run: |
        rm -rf predictive-maintenance/deploy/__pycache__
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r predictive-maintenance/requirements.txt
    
    - name: Prepare model directory
      run: mkdir -p predictive-maintenance/models

    - name: Train model
      run: |
        python predictive-maintenance/src/train.py predictive-maintenance/data/engine_data.csv

    - name: Run_deployment
      env:
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      run: python predictive-maintenance/deploy/deploy.py


      #gmil
